#ifndef REGION_EXP_HPP
#define REGION_EXP_HPP

enum RegionException {
	INDEX_OUT_OF_LIMS,
	COLUMN_COORD_NOT_MATCHED,
	ROW_COORD_NOT_MATCHED,
	ROW_COL_ALREADY_UPDATED,
	INNER_BOUNDARY_ALREADY_UPDATED,
	INVALID_LINEAR_REGION,
	INVALID_BOUNDARY
};

#endif